### ISSUE TITLE
Why can not I use the files in node_modules?

### ISSUE THREAD

**Issue by goldenthumb** [pveyes/raw.macro#15]
I want to use like below.
const file = raw("library_name/raw_file");

I use 'preval.macro' to solve the problem.
const file preval\`module.exports = require('fs').readFileSync(require.resolve('library_name/raw_file'), 'utf-8')\`;

**Comment by pveyes** [comment]
This is due to path resolution using `path.resolve` instead of `require.resolve`. See https://github.com/pveyes/raw.macro/blob/master/src/macro.js#L41

**Comment by pveyes** [comment]
Closed via #17
