### ISSUE TITLE
Avoid or clear babel cache

### ISSUE THREAD

**Issue by loopmode** [pveyes/raw.macro#20]
Thanks for this cool and useful package.
I use it to include the "own source code" of components in a react application.

However, when I change the component sources, the changes do not get reflected.
What's annoying is that even restarting the webpack-dev-server does not help - I have to stop the server, explicitly run `rm -rf node_modules/.cache`, then start again.

Can you think of any clever way I can avoid caching from userland?
Otherwise, can you think of how to implement such behaviour in `raw.macro` itself?

**Comment by pveyes** [comment]
Yeah, unfortunately this is an inherent problem with all babel plugin macros that depend on external file as seen https://github.com/kentcdodds/babel-plugin-macros#caveats

For now my recommendation would be to modify the source code that includes macro by adding comment

**Comment by loopmode** [comment]
Aah, so if the including file changes, the included one is "part of it" and will be invalidated.. Didn't think of that, thanks!
