### ISSUE TITLE
Linked website is down

### ISSUE THREAD

**Issue by zaydek** [pveyes/raw.macro#27]
Just a heads up that the URL for the repo responds with a Server Error 500 status code.

https://fatihkalifa.com/implementing-webpack-rawloader-as-babelpluginmacros-baf5955d27e8

**Comment by pveyes** [comment]
Oh shoot, thanks for reporting

**Comment by zaydek** [comment]
Hey this works! 🎉

https://fatihkalifa.com/implementing-webpack-rawloader-as-babelpluginmacros

You can drop the hash after the slug.

**Comment by pveyes** [comment]
It should still work even with a slug, but I haven't been able to find the root cause, so I removed the hash. Thanks
