### ISSUE TITLE
ENOTDIR: not a directory using template literal.

### ISSUE THREAD

**Issue by justindmyers** [pveyes/raw.macro#40]
I'm trying out the latest dynamic import and am running into an issue where simply using a template literal (without variables) is throwing an error in a create-react-app and returns undefined when variables are added.

This works:
```const file = raw('../blocks/blog/a.css')```

This throws the error `raw.macro: ENOTDIR: not a directory, scandir`:
```const file = raw(`../blocks/blog/a.css`)```

The only difference is using a template literal instead of a single quote.

Once I add in variables, no errors are thrown, but it only returns undefined:
```const file = raw(`../blocks/${blockType}/${blockName}.css`)```

With some more testing, I'm guessing it seems to be a problem with the filename resolution. If I change the directory to an non-existent folder, an error is thrown. If I change the filename to an non-existent file, no error is thrown, it just returns undefined.

This does not throw an error
```const rawCss = raw(`../blocks/${blockType}/thisfiledoesnotexist.css`);```

This does:
```const rawCss = raw(`../blocks/thisfolderdoesnotexist/a.css`);```

**Comment by pveyes** [comment]
Nice catch, I forgot to handle the the first case (using static template literals). Will create a PR to fix this

I'm still unsure about the second case. Did you mean that it works as intended but for invalid case it doesn't throw error?

**Comment by justindmyers** [comment]
No, it seems to ignore the file completely in my second case. A valid or invalid file is returning undefined.

If the directory is wrong though, it correctly throws an error. The actual file just seems be ignored.

**Comment by pveyes** [comment]
For invalid file name, yes, it's not handled yet. I just made PR to throw error on build time

For valid case, I don't think this is expected as you can see here https://github.com/pveyes/raw.macro/blob/f0665bb8c837ad8627ba4d13c7eb2eb0a5a42f47/src/__tests__/__snapshots__/macro.test.js.snap#L24-L45 the object `__raw_dynamic__0` has correct key value pairs

**Comment by pveyes** [comment]
Update: my bad, just realized that there are bug where if you use multiple dynamic values and omitting the extension, the object map is created with the wrong keys. https://github.com/pveyes/raw.macro/blob/f0665bb8c837ad8627ba4d13c7eb2eb0a5a42f47/src/__tests__/__snapshots__/macro.test.js.snap#L80-L94 here it should use `post` as key instead of `post.md` 

I've fixed the bug in the same PR https://github.com/pveyes/raw.macro/pull/42/commits/b0e91d8981036cc8c779457413683871feaba438
