### ISSUE TITLE
i got this err

### ISSUE THREAD

**Issue by zhyuzh3d** [pveyes/raw.macro#51]
./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/index.js
Module parse failed: Unexpected token (68:30)
You may need an appropriate loader to handle this file type.
|     loaders: defaultLoaders
|   };
|   const normalizedOptions = { ...defaults,
|     ...options,
|     loaders: { ...defaults.loaders,

**Comment by zhyuzh3d** [comment]
with react-create-app

**Comment by pveyes** [comment]
Can you share minimal repro case in another repo or using codesandbox? thanks
