### ISSUE TITLE
Paths with spaces not working.

### ISSUE THREAD

**Issue by charlesomer** [pveyes/raw.macro#52]
Hi,

I'm currently able to do this:
`console.log(raw('./MD with space.md'));`

But not this:
```console.log(raw(`./${file}`));```
where file is `MD with space.md`.

Is there a way to get this working?

Thank you!

**Comment by charlesomer** [comment]
Hmm, it also seems I can't import from more than just the first folder I try, is this expected behaviour?

My basic setups involves a file with an array of MD files I need to import to use in react. Which could involve multiple subdirectories etc.

**Comment by pveyes** [comment]
> Hi,
> 
> I'm currently able to do this:
> `console.log(raw('./MD with space.md'));`
> 
> But not this:
> `` console.log(raw(`./${file}`)); ``
> where file is `MD with space.md`.
> 
> Is there a way to get this working?
> 
> Thank you!

What kind of setup do you have? (OS, node version, etc). I just tried it in macOS node v14 and it works fine, I also created a draft PR https://github.com/pveyes/raw.macro/pull/53 and you can see that the new test case passed.

You can try submitting PR with a failing test case and I'll take a look

> Hmm, it also seems I can't import from more than just the first folder I try, is this expected behaviour?
> 
> My basic setups involves a file with an array of MD files I need to import to use in react. Which could involve multiple subdirectories etc.

Yes, that's the limitation as described in the [README](https://github.com/pveyes/raw.macro#dynamic-path-import)

> **This method has 2 caveats:**
>
> 1. You can only use up to two variables inside template literal. 1 for directory name, and 1 for file name.

**Comment by charlesomer** [comment]
I'm using macOS (11.4), ReactJS (17.0.2), Node (v16.4.1)

> Yes, that's the limitation as described in the README

Ah okay, I only have one variable with the path but it can have any type of route with any amount of subdirectories so I wasn't sure if this applied in this case.

I've just tried the following:
```

  let array = [
    'README.md', 'More Info.md', 'Example Setups.md', 'Build Info/Info file.md'
  ]

  array.forEach(element => {
    console.log(raw(`./markdown/${element}`));
  });
```

And it worked, except the file in the subdirectory which could be why they were all failing in my real use case. So I'll just have to keep using `fetch` I think to work around this for now :)

Thank you for your help!
